build:
  version: "3.0"

goku:
  message: "Welcome to Goku Related APIs"
  contactDetails:
    name: "Abhijeet Singh"
    email: "abhi@gmail.com"
  onCallSupport:
    - (555)555-1234
    - (555)123-8765

vegeta:   # This name tag is mapped to @ConfigurationProperties name tag
  message: "Welcome to Vegeta Related APIs"
  contactDetails:
    name: "Abhijeet Singh"
    email: "abhi@gmail.com"
  onCallSupport:
    - (555)555-1234
    - (555)123-8765